//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Production
    {
        public int ID { get; set; }
        public string PD_SO { get; set; }
        public string PD_Machine { get; set; }
        public string PD_Type { get; set; }
        public Nullable<double> PD_Qty { get; set; }
        public string PD_Process { get; set; }
        public string PD_CuttingLength { get; set; }
        public Nullable<double> PD_Qty_T { get; set; }
        public Nullable<double> PD_Speed { get; set; }
        public Nullable<System.DateTime> PD_Import_Date { get; set; }
    }
}
