//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Machine
    {
        public int ID { get; set; }
        public string MC_Machine { get; set; }
        public string MC_Process { get; set; }
        public string MC_Status { get; set; }
        public string MC_Code { get; set; }
    }
}
