//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Routing_SQS
    {
        public int ID { get; set; }
        public string Process { get; set; }
        public string WorkCenter { get; set; }
        public string MasterProcess { get; set; }
    }
}
