//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Metal
    {
        public int ID { get; set; }
        public string Metal_Material { get; set; }
        public string Metal_Material_Des { get; set; }
        public string Metal_Type { get; set; }
        public string Metal_UOM { get; set; }
        public Nullable<double> Metal_AI_W_U { get; set; }
        public Nullable<double> Metal_CU_W_U { get; set; }
        public Nullable<double> Metal_Netweight_W_U { get; set; }
        public Nullable<double> Metal_Netweight_W_0_U { get; set; }
    }
}
