//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Speed_Machine
    {
        public int ID { get; set; }
        public string Machine { get; set; }
        public string Process { get; set; }
        public string Type { get; set; }
        public Nullable<double> Speed { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string Time_Change { get; set; }
    }
}
