//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_SO
    {
        public int ID { get; set; }
        public string SO { get; set; }
        public string Customer { get; set; }
        public string Material { get; set; }
        public string Material_Des { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public Nullable<System.DateTime> Date_PFD { get; set; }
        public Nullable<System.DateTime> Date_Delivery { get; set; }
        public Nullable<double> Order_QTY { get; set; }
        public Nullable<double> FG_QTY { get; set; }
        public string Unit { get; set; }
    }
}
