//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Data
    {
        public int ID { get; set; }
        public string B_SO { get; set; }
        public string B_PO { get; set; }
        public string B_Customer { get; set; }
        public string B_Material { get; set; }
        public string B_Material_Des { get; set; }
        public string Date_Create { get; set; }
        public string Date_PFD { get; set; }
        public string Date_Delivery { get; set; }
        public string B_Cutting_Length { get; set; }
        public Nullable<double> B_Order_QTY { get; set; }
        public string B_Order_Unit { get; set; }
        public string PL_Machine { get; set; }
        public string PL_Process { get; set; }
        public string PL_Type { get; set; }
        public Nullable<double> PL_Qty { get; set; }
        public string PL_Tag { get; set; }
        public Nullable<double> PL_Qty_T { get; set; }
        public string PL_Color { get; set; }
    }
}
