//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTIF_TR_MoveLocation
    {
        public int ID { get; set; }
        public string Move_TAG { get; set; }
        public string Move_User { get; set; }
        public Nullable<System.DateTime> Move_Date { get; set; }
        public Nullable<System.TimeSpan> Move_time { get; set; }
        public string Move_Status { get; set; }
        public string Move_Loca { get; set; }
        public string Move_Alert { get; set; }
    }
}
