//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTIF_TR_Machine_Monitor
    {
        public int ID { get; set; }
        public string Monitor_Machine { get; set; }
        public Nullable<System.DateTime> Monitor_DateTime { get; set; }
        public string Monitor_Time { get; set; }
    }
}
