//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTIF_TR_Packing
    {
        public int ID { get; set; }
        public string Pack_SO { get; set; }
        public string Pack_Machine { get; set; }
        public string Pack_Tag { get; set; }
        public string Pack_Status { get; set; }
        public Nullable<double> Pack_QTY { get; set; }
        public Nullable<double> Pack_QTY_Balance { get; set; }
        public Nullable<int> Pack_LVL { get; set; }
        public Nullable<System.DateTime> Pack_Create { get; set; }
        public Nullable<System.TimeSpan> Pack_Create_time { get; set; }
        public Nullable<System.DateTime> Pack_Update { get; set; }
        public Nullable<System.DateTime> Pack_QC_Update { get; set; }
        public Nullable<double> Pack_Speed { get; set; }
        public Nullable<System.DateTime> Pack_DateTime { get; set; }
        public string Pack_Reel_Size { get; set; }
        public string Pack_Status_Shop { get; set; }
        public string Pack_Status_QC { get; set; }
        public string Pack_QC_User { get; set; }
        public string Pack_Base { get; set; }
        public Nullable<double> Pack_Weight { get; set; }
        public Nullable<double> Pack_ReelNo { get; set; }
        public Nullable<double> Pack_Gross { get; set; }
    }
}
