//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTIF_TR_ShopFloor
    {
        public int ID { get; set; }
        public string SF_Kanban { get; set; }
        public string SF_Machine { get; set; }
        public string SF_User { get; set; }
        public Nullable<int> SF_QTY { get; set; }
        public Nullable<System.DateTime> SF_Date { get; set; }
        public Nullable<System.TimeSpan> SF_Time { get; set; }
        public Nullable<double> SF_Actual_Speed { get; set; }
        public string SF_Stop_Process { get; set; }
        public string SF_Stop_Code { get; set; }
        public Nullable<System.TimeSpan> SF_Time_Fst { get; set; }
    }
}
