//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTIF_TR_Cal
    {
        public int ID { get; set; }
        public string Cal_SO { get; set; }
        public string Cal_Machine { get; set; }
        public string Cal_Tag { get; set; }
        public string Cal_Status { get; set; }
        public Nullable<double> Cal_QTY { get; set; }
        public Nullable<double> Cal_QTY_Balance { get; set; }
        public Nullable<int> Cal_LVL { get; set; }
        public Nullable<System.DateTime> Cal_Create { get; set; }
        public Nullable<System.TimeSpan> Cal_Create_time { get; set; }
        public Nullable<System.DateTime> Cal_Update { get; set; }
        public Nullable<System.TimeSpan> Cal_Update_time { get; set; }
        public Nullable<double> Cal_Speed { get; set; }
    }
}
