//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqProduction
    {
        public string Operation { get; set; }
        public string WorkCenter { get; set; }
        public double ConsumeHour { get; set; }
        public double DL { get; set; }
        public double VOH { get; set; }
        public string BasisCode { get; set; }
        public double Setup { get; set; }
        public double Run { get; set; }
        public double Speed { get; set; }
        public double ProductionRate { get; set; }
        public double BOMReq { get; set; }
        public int OperationCode { get; set; }
        public string WorkCenterCode { get; set; }
        public double FixVOH { get; set; }
        public double Depreciation { get; set; }
        public string FacilityCode { get; set; }
        public string ItemNumber { get; set; }
        public string LastMaintainUser { get; set; }
        public System.DateTime LastMaintainDate { get; set; }
        public int SequenceNumber { get; set; }
        public int BubbleNumber { get; set; }
        public bool DummyFlag { get; set; }
        public string OwnerOfOperation { get; set; }
        public double BatchSizeOfOwner { get; set; }
        public double LotSizeOfOwner { get; set; }
        public double SetupHour { get; set; }
        public double RunHour { get; set; }
        public double MachineHour { get; set; }
        public double OutsideCost { get; set; }
        public string TypeOfParent { get; set; }
        public string ClassOfParent { get; set; }
        public string UOMOfParent { get; set; }
        public double BatchSizeOfParent { get; set; }
        public double LotSizeOfParent { get; set; }
        public int LoadingCode { get; set; }
        public double WIPQuantityRequired { get; set; }
        public Nullable<decimal> StdMacSpeed { get; set; }
    }
}
