//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTIF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WMS_PDEntities : DbContext
    {
        public WMS_PDEntities()
            : base("name=WMS_PDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WMS_PD_Master_SO> WMS_PD_Master_SO { get; set; }
        public virtual DbSet<WMS_PD_Product> WMS_PD_Product { get; set; }
    }
}
